apiVersion: v1
kind: Service
metadata:
  labels:
    app: magento
  name: magento-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: magento
  type: LoadBalancer

