variable "eks-node-role-name" {}
variable "node-instance-profile" {}
variable "eks-node-securitygroup" {}
variable "vpc_id" {}
variable "aws_subnet" {}
variable "cluster-name" {}
variable "eks-securitygroup" {}
variable "arn" {}
variable "endpoint" {}
variable "certificate" {}
variable "worker_ami_name_filter" {}
variable "worker_ami_owner_id" {}
variable "instance_type" {}
variable "name_prefix" {}
variable "num-workers" {}
variable "num-max-workers" {}
variable "num-min-workers" {}
variable "alb-name" {}
variable "spot_price" {}
variable "key_name" {}
